@AuthService.API_HostAddress = https://localhost:7192/api

POST {{AuthService.API_HostAddress}}/auth/login
Accept: application/json
content-type: application/json

{
    "email": "user@gmail.com",
    "password": "User@12345678"
}
